# Cloudflare Workers configuration
# Quick start: npx wrangler dev
# OR
# Install wrangler: npm install -g wrangler
# Deploy: wrangler deploy

name = "decide-pe-home"
#main = "worker/api.ts"
compatibility_date = "2025-04-01"
workers_dev = false
preview_urls = false

# SPA configuration for serving React app
[assets]
not_found_handling = "single-page-application"
# directory = "./dist"
# Not needed if using Vite plugin. See https://developers.cloudflare.com/workers/wrangler/configuration/#assets


[route]
pattern = "decide.pe"
zone_name = "decide.pe"
custom_domain = true
